baseURL = "https://imjoshholloway.uk/"
languageCode = "en-gb"
title = "Josh Holloway"
theme = "hello-friend-ng"
googleAnalytics = "UA-167963804-1"

[menu]
  [[menu.main]]
    name = "Resume"
    identifier = "resume"
    url = "/resume.pdf"
    weight = -110

  [[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "posts/"

[params]
  homeSubtitle = "Father // Husband // Software Engineer"

  [params.portrait]
    path     = "/images/profile.jpg"
    alt      = "Portrait"
    maxWidth = "150px"

  # Add additional social link entries underneath
  [[params.social]]
    name = "twitter"
    url  = "https://www.twitter.com/imjoshholloway"
  [[params.social]]
    name = "github"
    url  = "https://www.github.com/imjoshholloway"
  [[params.social]]
    name = "linkedin"
    url = "https://uk.linkedin.com/in/imjoshholloway"
